name: flutter_test_goldens
description: "A toolkit for writing golden tests"
version: 0.0.1
homepage: https://github.com/Flutter-Bounty-Hunters/flutter_test_goldens
repository: https://github.com/Flutter-Bounty-Hunters/flutter_test_goldens

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  golden_bricks: ^1.0.0
  image: ^4.5.4
  logging: ^1.3.0
  meta: ^1.15.0
  path: ^1.9.0
  qr_bar_code: ^1.3.0
  zxing2: ^0.2.3

dev_dependencies:
  flutter_lints: ^5.0.0

  flutter_test_robots: ^0.0.24
  flutter_test_runners: ^0.0.4
  lucid:
    git:
      url: git@github.com:Flutter-Bounty-Hunters/lucid.git

flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: packages/flutter_test_goldens/assets/fonts/OpenSans-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
