name: PR Validation
on:
  pull_request:

jobs:
  build_website:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./doc/website
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup a Dart environment
      - uses: dart-lang/setup-dart@v1

      # Download all the packages that the app uses
      - run: dart pub get

      # Build the static site.
      - run: dart run bin/main.dart
