name: PR Validation
on:
  pull_request:

jobs:
  test_goldens:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Download all the packages that the app uses
      - run: flutter pub get

      # Run all tests
      - run: flutter test test_goldens

      # Archive golden failures
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: golden-failures
          path: "**/failures/**/*.png"

  build_website:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./doc/website
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup a Dart environment
      - uses: dart-lang/setup-dart@v1

      # Download all the packages that the app uses
      - run: dart pub get

      # Build the static site.
      - run: dart run bin/main.dart
